import Footer from '@/Components/footer'
import '../../styles/global.css'

// layout.tsx
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='h-[100vh] z-0'>{children}</body>
      <Footer /> 
    </html>
  )
}
