import Footer from '@/Components/footer'
import '../../styles/global.css'

// layout.tsx
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=' z-0'>
      <div className="min-h-screen h-full">{children}</div>
      <Footer/>
      </body>
      
    </html>
  )
}
